#!/usr/bin/bash
# This program is in the public domain

if [[ -z $CACHE_DIRECTORY ]] || [[ -z $1 ]]; then
	exit
fi

for s in ${CACHE_DIRECTORY//:/ }; do
	d=${s#/var/cache/btrfs-snapshot}
	btrfs --verbose subvolume snapshot -r "$d" "$s/$(date +"$1")"
done
